user_authentification:
    prefix: /authentication
    resource: "@CoOperationUserBundle/Resources/config/routing/authentication.yml"

admin_user:
    prefix: /admin/user
    resource: "@CoOperationUserBundle/Resources/config/routing/user.yml"
