services:
    CoOperation\Bundle\UserBundle\Controller\AuthenticationController:
        arguments: ['@Symfony\Component\Security\Http\Authentication\AuthenticationUtils', '@security.password_encoder']
