core:
    resource: "@CoOperationCoreBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@CoOperationUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
