# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        CoOperation\Bundle\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_USER: ~
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        cooperation_provider:
            entity:
                class: CoOperationUserBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: cooperation_provider
            logout_on_user_change: true
            anonymous: ~
            form_login:
                csrf_token_generator: security.csrf.token_manager
                default_target_path: core_homepage
                login_path: user_login
                check_path: user_login
            logout:
                success_handler: cooperation.handler.logout_success_handler
                path: /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
