list_index:
    path: /
    defaults:
        _controller: CoOperationListBundle:List:index

list_new:
    path: /newlist
    defaults:
        _controller: CoOperationListBundle:List:new

list_view:
    path: /viewlist/{id}
    defaults:
        _controller: CoOperationListBundle:List:view
  #  requierements:
  #      id: /d+/

group_new:
    path: /newgroup
    defaults:
        _controller: CoOperationGroupBundle:Group:new

group_view:
    path: /viewgroup/{id}
    defaults:
        _controller: CoOperationGroupBundle:Group:view
  #  requierements:
  #      id: /d+/

account_new:
    path: /newaccount
    defaults:
        _controller: CoOperationAccountBundle:Account:new

account_view:
    path: /viewaccount/{id}
    defaults:
        _controller: CoOperationAccountBundle:Account:view
    #  requierements:
    #      id: /d+/
